=== api-evangelist/paytronix/json-schema/online-ordering-api-menu-item-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "MenuItem",
  "description": "MenuItem schema from Paytronix Online Ordering API",
  "$id": "https://raw.githubusercontent.com/api-evangelist/paytronix/refs/heads/main/json-schema/online-ordering-api-menu-item-schema.json",
  "type": "object",
  "properties": {
    "id": {
      "type": "string",
      "example": "4b96f1bafc9f100ca79231ef"
    },
    "name": {
      "type": "string",
      "example": "Chicken Burrito"
    },
    "description": {
      "type": "string",
      "example": "Grilled chicken, rice, beans, salsa"
    },
    "imageUrl": {
      "type": "string"
    },
    "prices": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string",
            "example": "Regular"
          },
          "price": {
            "type": "number",
            "example": 9.5
          }
        }
      }
    },
    "options": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string",
            "example": "Add Guacamole"
          },
          "price": {
            "type": "number",
            "example": 1.5
          }
        }
      }
    }
  }
}

=== api-evangelist/paytronix/examples/online-ordering-api-menu-item-example.json
{
  "id": "4b96f1bafc9f100ca79231ef",
  "name": "Chicken Burrito",
  "description": "Grilled chicken, rice, beans, salsa",
  "imageUrl": "string",
  "prices": [
    {
      "name": "Regular",
      "price": 9.5
    }
  ],
  "options": [
    {
      "name": "Add Guacamole",
      "price": 1.5
    }
  ]
}
