=== api-evangelist/paytronix/json-schema/server-api-add-redeem-request-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "AddRedeemRequest",
  "description": "AddRedeemRequest schema from Paytronix Server API",
  "$id": "https://raw.githubusercontent.com/api-evangelist/paytronix/refs/heads/main/json-schema/server-api-add-redeem-request-schema.json",
  "type": "object",
  "properties": {
    "headerInfo": {
      "$ref": "#/components/schemas/HeaderInfo"
    },
    "cardInfo": {
      "$ref": "#/components/schemas/CardInfo"
    },
    "addWalletContents": {
      "type": "array",
      "items": {
        "$ref": "#/components/schemas/WalletContent"
      }
    },
    "redeemWalletContents": {
      "type": "array",
      "items": {
        "$ref": "#/components/schemas/WalletContent"
      }
    }
  },
  "required": [
    "headerInfo",
    "cardInfo"
  ]
}

=== api-evangelist/paytronix/examples/server-api-add-redeem-request-example.json
{
  "headerInfo": {
    "merchantId": 1000,
    "storeCode": "1",
    "programId": "PX",
    "terminal": "1",
    "operator": "100",
    "posTransactionId": "string"
  },
  "cardInfo": {
    "printedCardNumber": "60490012345678",
    "magstripe": "string",
    "cardTemplateCode": "1"
  },
  "addWalletContents": [
    {
      "walletCode": "1",
      "quantity": 10,
      "expiration": "2026-06-03"
    }
  ],
  "redeemWalletContents": [
    {
      "walletCode": "1",
      "quantity": 10,
      "expiration": "2026-06-03"
    }
  ]
}
