=== api-evangelist/paytronix/json-schema/server-api-create-and-register-request-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "CreateAndRegisterRequest",
  "description": "CreateAndRegisterRequest schema from Paytronix Server API",
  "$id": "https://raw.githubusercontent.com/api-evangelist/paytronix/refs/heads/main/json-schema/server-api-create-and-register-request-schema.json",
  "type": "object",
  "properties": {
    "merchantId": {
      "type": "integer",
      "example": 1000
    },
    "cardTemplateCode": {
      "type": "string",
      "example": "1"
    },
    "enforceUniqueFields": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "example": [
        "email"
      ]
    },
    "setUserFields": {
      "type": "object",
      "additionalProperties": true,
      "example": {
        "username": "jdoe",
        "password": "s3cret",
        "firstName": "Jane",
        "lastName": "Doe",
        "email": "jane@example.com"
      }
    },
    "setAccountFields": {
      "type": "object",
      "additionalProperties": true
    },
    "sendSmsVerification": {
      "type": "boolean"
    },
    "smsVerificationCode": {
      "type": "string"
    }
  },
  "required": [
    "merchantId",
    "cardTemplateCode",
    "setUserFields"
  ]
}

=== api-evangelist/paytronix/examples/server-api-create-and-register-request-example.json
{
  "merchantId": 1000,
  "cardTemplateCode": "1",
  "enforceUniqueFields": [
    "email"
  ],
  "setUserFields": {
    "username": "jdoe",
    "password": "s3cret",
    "firstName": "Jane",
    "lastName": "Doe",
    "email": "jane@example.com"
  },
  "setAccountFields": {},
  "sendSmsVerification": true,
  "smsVerificationCode": "string"
}
